In [ ]:
import requests
import pandas as pd
from requests.structures import CaseInsensitiveDict
from pytz import timezone
from datetime import datetime
import json

url = "'<enter firebase url>' + the path like shown in the video"



headers = CaseInsensitiveDict()
headers["Content-Type"] = "application/json"

resp = requests.get(url, headers=headers)
print(resp.status_code)
print(resp.reason)
#print(resp)
print(resp.json())

mystring = (resp.json())

#print(type(mystring))

#print(mystring)

df = pd.DataFrame(mystring)
df.head()

200
OK
[{'count': '19', 'group': 'Google BigQuery', 'id': 0}, {'count': '2', 'group': 'Big Data & Machine Learning 101', 'id': 1}, {'count': '10', 'group': 'Pet and Play Python & Machine Learning', 'id': 2}, {'count': '18', 'group': 'TensorFlow 2.2', 'id': 3}, {'count': '0', 'group': 'Power BI', 'id': 4}, {'count': '0', 'group': 'Machine Learning - R', 'id': 5}, {'count': '0', 'group': 'Computer Vision - OpenCV', 'id': 6}, {'count': '0', 'group': 'IBM Chatbot', 'id': 7}, {'count': '0', 'group': 'AI - Deep Learning', 'id': 8}, {'count': '0', 'group': 'Tableau', 'id': 9}, {'count': '0', 'group': 'AWS', 'id': 10}, {'count': '0', 'group': 'Microsoft Azure:', 'id': 11}, {'count': '0', 'group': 'IBM Predictive Analytics', 'id': 12}, {'count': '0', 'group': 'Quantum Computing - ML', 'id': 13}]

  count                                   group  id
0    19                         Google BigQuery   0
1     2         Big Data & Machine Learning 101   1
2    10  Pet and Play Python & Machine Learning   2
3    18                          TensorFlow 2.2   3
4     0                                Power BI   4